SELECT LAST_UPDATE FROM actor;
SELECT last_update, DATE_FORMAT(last_update, '%D %M %Y') FROM actor;



SELECT SYSDATE();
SELECT DAYOFMONTH();
SELECT CURTIME();   
SELECT YEARWEEK(CURDATE());
SELECT YEARWEEK('2024-11-11');


